title: <p align="center">Mamatha Shetty</p>
logo: /assets/img/Mamatha.png
description: <p align="center">
  |
  <a href="https://www.linkedin.com/in/mamathashetty/">LinkedIn</a> |
  <a href="https://github.com/mamathashettty">GitHub</a>
  
  <br>   
      I am working as associate Manager at Accenture, Mumbai.
      
      Currently pursuing post graduation in Artificial Intelligence and Machine Learning from IIITB, Banglore.
  <br>
  </p>
  
  
  
  
  
theme: jekyll-theme-minimal
      
